import { TowerBlueprint } from "../types";

// Hero tier towers (starter towers)
export const heroTowers: TowerBlueprint[] = [
  {
    id: "archer",
    name: "Archer",
    tier: "hero",
    type: "archer",
    damage: 10,
    range: 8,
    attackSpeed: 1, // 1 attack per second
    cost: 50,
    upgradeCost: 100,
    upgradeName: "Marksman",
    description: "Ranged attacker with good range and attack speed. Upgrades to Sun Herald, then Apollo.",
    color: "#8bc34a", // Light green
    upgradeChain: ["marksman", "apollo"]
  },
  {
    id: "warrior",
    name: "Warrior",
    tier: "hero",
    type: "warrior",
    damage: 25,
    range: 3,
    attackSpeed: 0.7, // 0.7 attacks per second
    cost: 75,
    upgradeCost: 150,
    upgradeName: "Hoplite",
    description: "Strong melee attacker with high damage but short range. Upgrades to Champion, then Heracles.",
    color: "#f44336", // Red
    upgradeChain: ["hoplite", "heracles"]
  },
  {
    id: "mage",
    name: "Mage",
    tier: "hero",
    type: "mage",
    damage: 15,
    range: 6,
    attackSpeed: 0.8, // 0.8 attacks per second
    cost: 65,
    upgradeCost: 125,
    upgradeName: "Sorcerer",
    description: "Magical attacker with area of effect damage. Upgrades to Enchantress, then Circe.",
    color: "#2196f3", // Blue
    upgradeChain: ["sorcerer", "circe"]
  },
  {
    id: "enchanter",
    name: "Enchanter",
    tier: "hero",
    type: "enchanter",
    damage: 8,
    range: 7,
    attackSpeed: 1.2, // 1.2 attacks per second
    cost: 70,
    upgradeCost: 140,
    upgradeName: "Charmer",
    description: "Crowd control specialist that can slow and charm enemies. Upgrades to Charmer, then Aphrodite.",
    color: "#E91E63", // Pink
    upgradeChain: ["charmer", "aphrodite"]
  },
  {
    id: "thunderer",
    name: "Thunderer",
    tier: "hero",
    type: "lightning",
    damage: 12,
    range: 5,
    attackSpeed: 0.9, // 0.9 attacks per second
    cost: 60,
    upgradeCost: 120,
    upgradeName: "Storm Caller",
    description: "Harnesses lightning to strike multiple targets in a chain. Upgrades to Storm Caller, then Zeus.",
    color: "#FFC107", // Amber
    upgradeChain: ["stormcaller", "zeus"]
  },
  {
    id: "tide",
    name: "Tide Caller",
    tier: "hero",
    type: "water",
    damage: 18,
    range: 4,
    attackSpeed: 0.8, // 0.8 attacks per second
    cost: 65,
    upgradeCost: 130,
    upgradeName: "Wave Mage",
    description: "Manipulates water to push back and damage enemies. Upgrades to Wave Mage, then Poseidon.",
    color: "#03A9F4", // Light Blue
    upgradeChain: ["wavemage", "poseidon"]
  },
  // New hero towers for additional gods
  {
    id: "huntress",
    name: "Huntress",
    tier: "hero",
    type: "huntress",
    damage: 12,
    range: 9,
    attackSpeed: 1.1, // 1.1 attacks per second
    cost: 55,
    upgradeCost: 110,
    upgradeName: "Tracker",
    description: "Expert hunter with exceptional aim and tracking abilities. Upgrades to Tracker, then Artemis.",
    color: "#7cb342", // Olive green
    upgradeChain: ["tracker", "artemis"]
  },
  {
    id: "royalguard",
    name: "Royal Guard",
    tier: "hero",
    type: "queen",
    damage: 10,
    range: 5,
    attackSpeed: 0.9,
    cost: 60,
    upgradeCost: 120,
    upgradeName: "Regent",
    description: "Commander with tactical advantages and leadership skills.",
    color: "#9c27b0" // Purple
  },
  {
    id: "berserker",
    name: "Berserker",
    tier: "hero",
    type: "warlord",
    damage: 30,
    range: 2,
    attackSpeed: 0.6,
    cost: 80,
    upgradeCost: 160,
    upgradeName: "Warlord",
    description: "Fierce warrior who gains strength as battles intensify.",
    color: "#d50000" // Bright red
  },
  {
    id: "messenger",
    name: "Messenger",
    tier: "hero",
    type: "swift",
    damage: 8,
    range: 6,
    attackSpeed: 1.5,
    cost: 60,
    upgradeCost: 120,
    upgradeName: "Scout",
    description: "Fast attacker who boosts nearby allies with speed.",
    color: "#cddc39" // Lime
  },
  {
    id: "shadow",
    name: "Shadow Adept",
    tier: "hero",
    type: "shadow",
    damage: 14,
    range: 5,
    attackSpeed: 0.9,
    cost: 65,
    upgradeCost: 130,
    upgradeName: "Night Walker",
    description: "Mysterious figure who strikes from the shadows.",
    color: "#424242" // Dark grey
  },
  {
    id: "keeper",
    name: "Keeper",
    tier: "hero",
    type: "hearth",
    damage: 10,
    range: 4,
    attackSpeed: 0.8,
    cost: 55,
    upgradeCost: 110,
    upgradeName: "Guardian",
    description: "Protective presence that strengthens allies around it.",
    color: "#ff5722" // Deep orange
  },
  {
    id: "reveler",
    name: "Reveler",
    tier: "hero",
    type: "wine",
    damage: 12,
    range: 5,
    attackSpeed: 1.0,
    cost: 60,
    upgradeCost: 120,
    upgradeName: "Celebrant",
    description: "Chaotic fighter who sows confusion among enemies.",
    color: "#8e24aa" // Medium purple
  },
  {
    id: "mystic",
    name: "Mystic",
    tier: "hero",
    type: "witch",
    damage: 14,
    range: 6,
    attackSpeed: 0.7,
    cost: 65,
    upgradeCost: 130,
    upgradeName: "Occultist",
    description: "Wielder of arcane powers and ancient magic.",
    color: "#6a1b9a" // Deep purple
  }
];

// Demigod tier towers (mid-tier upgrades)
export const demigodTowers: TowerBlueprint[] = [
  {
    id: "marksman",
    name: "Marksman",
    tier: "demigod",
    type: "archer",
    damage: 25,
    range: 10.4,
    attackSpeed: 1.2,
    cost: 150,
    upgradeCost: 300,
    upgradeName: "Apollo",
    description: "Skilled archer with enhanced range and speed.",
    color: "#4caf50" // Green
  },
  {
    id: "hoplite",
    name: "Hoplite",
    tier: "demigod",
    type: "warrior",
    damage: 62.5,
    range: 3.9,
    attackSpeed: 0.84,
    cost: 225,
    upgradeCost: 450,
    upgradeName: "Heracles",
    description: "Elite warrior with devastating melee attacks.",
    color: "#d32f2f" // Dark red
  },
  {
    id: "sorcerer",
    name: "Sorcerer",
    tier: "demigod",
    type: "mage",
    damage: 37.5,
    range: 7.8,
    attackSpeed: 0.96,
    cost: 190,
    upgradeCost: 375,
    upgradeName: "Circe",
    description: "Powerful mage with magical area attacks.",
    color: "#1976d2" // Dark blue
  },
  {
    id: "charmer",
    name: "Charmer",
    tier: "demigod",
    type: "enchanter",
    damage: 20,
    range: 9.1,
    attackSpeed: 1.44,
    cost: 210,
    upgradeCost: 420,
    upgradeName: "Aphrodite",
    description: "Master of attraction with the ability to charm enemies into temporary confusion.",
    color: "#C2185B" // Darker pink
  },
  {
    id: "stormcaller",
    name: "Storm Caller",
    tier: "demigod",
    type: "lightning",
    damage: 30,
    range: 6.5,
    attackSpeed: 1.08,
    cost: 180,
    upgradeCost: 360,
    upgradeName: "Zeus",
    description: "Commands powerful thunderstorms that chain between enemies.",
    color: "#FF8F00" // Darker amber
  },
  {
    id: "wavemage",
    name: "Wave Mage",
    tier: "demigod",
    type: "water",
    damage: 45,
    range: 5.2,
    attackSpeed: 0.96,
    cost: 195,
    upgradeCost: 390,
    upgradeName: "Poseidon",
    description: "Controls currents and tides to push enemies backward.",
    color: "#0288D1" // Darker blue
  },
  // New demigod towers
  {
    id: "tracker",
    name: "Tracker",
    tier: "demigod",
    type: "huntress",
    damage: 30,
    range: 11.7,
    attackSpeed: 1.32,
    cost: 165,
    upgradeCost: 330,
    upgradeName: "Artemis",
    description: "Master of the hunt who never loses her target.",
    color: "#558b2f" // Darker olive
  },
  {
    id: "regent",
    name: "Regent",
    tier: "demigod",
    type: "queen",
    damage: 25,
    range: 6.5,
    attackSpeed: 1.08,
    cost: 180,
    upgradeCost: 360,
    upgradeName: "Hera",
    description: "Royal commander who inspires allies and controls enemies.",
    color: "#7b1fa2" // Darker purple
  },
  {
    id: "warlord",
    name: "Warlord",
    tier: "demigod",
    type: "warlord",
    damage: 75,
    range: 2.6,
    attackSpeed: 0.72,
    cost: 240,
    upgradeCost: 480,
    upgradeName: "Ares",
    description: "Brutal combatant who gains strength in the thick of battle.",
    color: "#b71c1c" // Darker red
  },
  {
    id: "scout",
    name: "Scout",
    tier: "demigod",
    type: "swift",
    damage: 20,
    range: 7.8,
    attackSpeed: 1.8,
    cost: 180,
    upgradeCost: 360,
    upgradeName: "Hermes",
    description: "Lightning-fast fighter who enhances ally movement and attack speed.",
    color: "#afb42b" // Darker lime
  },
  {
    id: "nightwalker",
    name: "Night Walker",
    tier: "demigod",
    type: "shadow",
    damage: 35,
    range: 6.5,
    attackSpeed: 1.08,
    cost: 195,
    upgradeCost: 390,
    upgradeName: "Nyx",
    description: "Shrouded in darkness, striking with unseen precision.",
    color: "#212121" // Very dark grey
  },
  {
    id: "guardian",
    name: "Guardian",
    tier: "demigod",
    type: "hearth",
    damage: 25,
    range: 5.2,
    attackSpeed: 0.96,
    cost: 165,
    upgradeCost: 330,
    upgradeName: "Hestia",
    description: "Keeper of sacred flame who protects and empowers allies.",
    color: "#e64a19" // Darker orange
  },
  {
    id: "celebrant",
    name: "Celebrant",
    tier: "demigod",
    type: "wine",
    damage: 30,
    range: 6.5,
    attackSpeed: 1.2,
    cost: 180,
    upgradeCost: 360,
    upgradeName: "Dionysus",
    description: "Master of revelry who sows chaos and confusion among foes.",
    color: "#6a1b9a" // Darker purple
  },
  {
    id: "occultist",
    name: "Occultist",
    tier: "demigod",
    type: "witch",
    damage: 35,
    range: 7.8,
    attackSpeed: 0.84,
    cost: 195,
    upgradeCost: 390,
    upgradeName: "Hecate",
    description: "Wielder of dark arts and mysterious magical powers.",
    color: "#4a148c" // Very dark purple
  }
];

// Olympian tier towers (final upgrades)
export const olympianTowers: TowerBlueprint[] = [
  {
    id: "apollo",
    name: "Apollo",
    tier: "olympian",
    type: "archer",
    damage: 75,
    range: 15.6,
    attackSpeed: 1.8,
    cost: 450,
    upgradeCost: 0,
    upgradeName: null,
    description: "God of archery with deadly precision and sun powers.",
    color: "#ffd700" // Gold
  },
  {
    id: "heracles",
    name: "Heracles",
    tier: "olympian",
    type: "warrior",
    damage: 187.5,
    range: 5.85,
    attackSpeed: 1.26,
    cost: 675,
    upgradeCost: 0,
    upgradeName: null,
    description: "Legendary hero with godlike strength and endurance.",
    color: "#b71c1c" // Very dark red
  },
  {
    id: "circe",
    name: "Circe",
    tier: "olympian",
    type: "mage",
    damage: 112.5,
    range: 11.7,
    attackSpeed: 1.44,
    cost: 565,
    upgradeCost: 0,
    upgradeName: null,
    description: "Enchantress with powerful transformation magic.",
    color: "#0d47a1" // Very dark blue
  },
  {
    id: "aphrodite",
    name: "Aphrodite",
    tier: "olympian",
    type: "enchanter",
    damage: 60,
    range: 13.7,
    attackSpeed: 2.16,
    cost: 630,
    upgradeCost: 0,
    upgradeName: null,
    description: "Goddess of love who charms enemies and can control emotional states.",
    color: "#880E4F" // Very dark pink
  },
  {
    id: "zeus",
    name: "Zeus",
    tier: "olympian",
    type: "lightning",
    damage: 90,
    range: 9.75,
    attackSpeed: 1.62,
    cost: 540,
    upgradeCost: 0,
    upgradeName: null,
    description: "King of gods who wields devastating lightning bolts and chain strikes.",
    color: "#E65100" // Very dark amber
  },
  {
    id: "poseidon",
    name: "Poseidon",
    tier: "olympian",
    type: "water",
    damage: 135,
    range: 7.8,
    attackSpeed: 1.44,
    cost: 585,
    upgradeCost: 0,
    upgradeName: null,
    description: "God of the sea who creates massive tidal waves and water barriers.",
    color: "#01579B" // Very dark blue
  },
  // New Olympian towers
  {
    id: "artemis",
    name: "Artemis",
    tier: "olympian",
    type: "huntress",
    damage: 90,
    range: 17.55,
    attackSpeed: 1.98,
    cost: 495,
    upgradeCost: 0,
    upgradeName: null,
    description: "Goddess of the hunt with deadly precision and multi-target attacks.",
    color: "#33691e" // Very dark olive
  },
  {
    id: "hera",
    name: "Hera",
    tier: "olympian",
    type: "queen",
    damage: 75,
    range: 9.75,
    attackSpeed: 1.62,
    cost: 540,
    upgradeCost: 0,
    upgradeName: null,
    description: "Queen of Olympus who commands authority and controls the battlefield.",
    color: "#4a148c" // Very dark purple
  },
  {
    id: "ares",
    name: "Ares",
    tier: "olympian",
    type: "warlord",
    damage: 225,
    range: 3.9,
    attackSpeed: 1.08,
    cost: 720,
    upgradeCost: 0,
    upgradeName: null,
    description: "God of war with devastating strength and battlefield rage.",
    color: "#7f0000" // Blood red
  },
  {
    id: "hermes",
    name: "Hermes",
    tier: "olympian",
    type: "swift",
    damage: 60,
    range: 11.7,
    attackSpeed: 2.7,
    cost: 540,
    upgradeCost: 0,
    upgradeName: null,
    description: "Messenger god with unmatched speed and the ability to be anywhere instantly.",
    color: "#827717" // Very dark lime
  },
  {
    id: "nyx",
    name: "Nyx",
    tier: "olympian",
    type: "shadow",
    damage: 105,
    range: 9.75,
    attackSpeed: 1.62,
    cost: 585,
    upgradeCost: 0,
    upgradeName: null,
    description: "Primordial goddess of night who blinds enemies and strikes from shadows.",
    color: "#000000" // Black
  },
  {
    id: "hestia",
    name: "Hestia",
    tier: "olympian",
    type: "hearth",
    damage: 75,
    range: 7.8,
    attackSpeed: 1.44,
    cost: 495,
    upgradeCost: 0,
    upgradeName: null,
    description: "Goddess of the hearth who protects allies and wields sacred flame.",
    color: "#bf360c" // Very dark orange
  },
  {
    id: "dionysus",
    name: "Dionysus",
    tier: "olympian",
    type: "wine",
    damage: 90,
    range: 9.75,
    attackSpeed: 1.8,
    cost: 540,
    upgradeCost: 0,
    upgradeName: null,
    description: "God of wine and revelry who induces madness and confusion in enemies.",
    color: "#4a0072" // Very dark purple
  },
  {
    id: "hecate",
    name: "Hecate",
    tier: "olympian",
    type: "witch",
    damage: 105,
    range: 11.7,
    attackSpeed: 1.26,
    cost: 585,
    upgradeCost: 0,
    upgradeName: null,
    description: "Goddess of witchcraft and magic who casts powerful hexes and spells.",
    color: "#26004d" // Nearly black purple
  }
];

// All towers combined
export const allTowers = [...heroTowers, ...demigodTowers, ...olympianTowers];
